'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
type Receipt={id:string;packageId:string;fileName:string;mediaType:string;contentHash:string;note:string;createdAt:string}
export default function ReceiptFiles({projectId,packages,canUpload}:{projectId:string;packages:{id:string;projectVersion:number;submittedAt:string|null}[];canUpload:boolean}){
 const [rows,setRows]=useState<Receipt[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[packageId,setPackage]=useState(''),[note,setNote]=useState(''),[consent,setConsent]=useState(false);const retry=useRef<{fingerprint:string;key:string}|null>(null),base=`/api/grants/projects/${projectId}/receipts`
 const load=useCallback(async()=>{const r=await fetch(base,{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error||'Could not load receipt files');setRows(v.receipts)},[base])
 useEffect(()=>{let cancelled=false;fetch(base,{cache:'no-store'}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error||'Could not load receipt files');if(!cancelled)setRows(v.receipts)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[base])
 async function upload(){if(!file)return;setBusy(true);setError('');try{const bytes=await file.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>5000000)throw Error('Receipt must contain 1 byte to 5 MB');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join(''),fingerprint=JSON.stringify([packageId,note,file.name,file.type,digest]);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};const r=await fetch(base,{method:'POST',headers:{'Content-Type':file.type||'text/plain','X-Package-Id':packageId,'X-File-Name':encodeURIComponent(file.name),'X-Receipt-Note':encodeURIComponent(note),'X-Sharing-Confirmed':String(consent),'Idempotency-Key':retry.current.key},body:bytes}),v=await r.json();if(r.status<500)retry.current=null;if(!r.ok)throw Error(v.error||'Receipt upload failed');await load();setFile(null);setNote('');setConsent(false)}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 const button='rounded border px-3 py-2 disabled:opacity-50',field='block w-full rounded border p-2'
 return <section className="space-y-3 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Submission receipt files</h2><p>Attach the actual funder confirmation or supporting receipt to its recorded submission. Files remain private to project staff and reviewers. An uploaded file records your evidence; it does not verify a submission with the funder.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<button className={button} disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh receipt files</button>
 {canUpload&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void upload()}}><label>Recorded submission<select aria-label="Recorded submission" className={field} value={packageId} onChange={e=>setPackage(e.target.value)} required><option value="">Choose a submitted package</option>{packages.filter(p=>p.submittedAt).map(p=><option key={p.id} value={p.id}>Proposal version {p.projectVersion} · {new Date(p.submittedAt!).toLocaleString()}</option>)}</select></label><label>Receipt file (PDF, PNG, JPEG or UTF-8 text; up to 5 MB)<input className={field} required type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Receipt context and verification notes<textarea className={field} required minLength={10} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="block"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/> I am authorized to store this receipt and share it with this project’s staff and reviewers.</label><button className={button} disabled={busy||!file||!packageId||!consent}>Attach receipt file</button></form>}
 {rows.length===0&&<p>No receipt files attached.</p>}{rows.map(r=><article className="space-y-1 border-t pt-3" key={r.id}><a className="underline" href={base+'?receiptId='+encodeURIComponent(r.id)}>{r.fileName}</a><p>{r.note}</p><p className="break-all text-xs">SHA-256: {r.contentHash}</p></article>)}<p className="text-sm">Up to 10 files and 25 MB per submission package. Files are retained as an append-only evidence history; additional files can explain corrections.</p></section>
}
